"""Add is_deleted column to Ledger

Revision ID: 7d4537616e85
Revises: aaf70401bcb6
Create Date: 2023-01-15 12:49:28.148494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4537616e85'
down_revision = 'aaf70401bcb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledgers', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ledgers', 'is_deleted')
    # ### end Alembic commands ###
